---
title: "enrichment"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{enrichment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(SEMplR)
```

```{r}
# load our example variants
vars_df <- utils::read.delim("example_vars.csv", sep=",")[1:50, ]

# create vrange
vr <- VariantAnnotation::VRanges(seqnames = vars_df$seqnames,
              ranges = IRanges::IRanges(start=vars_df$start,
                                        end=vars_df$end),
              ref = vars_df$ref,
              alt = vars_df$alt)
# add the rsid to the metadata
vr$id <- vars_df$id
```

```{r}
# load SEMs from files
sems <- loadSEMs(sem_dir = "SEMs",
                 baseline_file = "SEMs/BASELINE/SEMs_baseline_norm.txt",
                 metadata_file =  "metadata.csv")
```

```{r}
plotMotif(sems, "MA0095.1") |> 
  ggsave(filename="~/Desktop/motif_plot.png",
         height = 3, width = 3)
```


```{r}
# score variants
sem_scores <- semMotifBinding(vr = vr, sems)
```

```{r}
plotSemMotifs(sem_scores, "rs9271608", label="tf_name")
plotSemMotifs(sem_scores, "rs12933575", label="tf_name") |>
  ggsave(filename = "~/Desktop/var_plot.png", height=4, width=4)
```


```{r}
# get the scores
scores(sem_scores)

# get the variants
variants(sem_scores)

# get sem metadata
sem_metadata(sem_scores)
```

```{r}
# calculate enrichment
enrich <- semEnrichment(sem_scores, 1000)
enrich
```

```{r}
# get the variants that gain the M01266 motif
motif_sub <- motifSub(sem_scores, "M01266")
motif_sub
```

```{r}
changed_motif(scores(motif_sub), "changed")
```

```{r}
top_sem <- rownames(enrich)[1]

sem_plt <- plotSemVariants(sempl_obj = sem_scores, 
                sem = "MA0095.1", 
                label = "varId") +
  ggplot2::ggtitle("YY1")
  ggsave(plot = sem_plt, filename = "~/Desktop/sem_plot.png",
         height=4, width=4)
```

